const form=document.querySelector('#assessment'),result=document.querySelector('#result'),langButton=document.querySelector('#lang');let lang='en';
const text=(en,es)=>lang==='en'?en:es;
langButton.addEventListener('click',()=>{lang=lang==='en'?'es':'en';langButton.textContent=lang==='en'?'ES':'EN';document.documentElement.lang=lang;document.querySelectorAll('[data-en]').forEach(el=>el.textContent=el.dataset[lang]);});
const checked=name=>[...document.querySelectorAll(`input[name="${name}"]:checked`)].map(x=>x.value);
form.addEventListener('submit',e=>{e.preventDefault();const prohibited=checked('prohibited'),transparency=checked('transparency'),product=document.querySelector('#product').checked,annex=document.querySelector('#annex').value,exception=document.querySelector('#exception').checked,name=document.querySelector('#name').value.trim(),role=document.querySelector('#role').value;let level,title,basis,actions=[];
if(prohibited.length){level='prohibited';title=text('Potential prohibited practice','Posible práctica prohibida');basis=`Article 5 · ${prohibited.join('; ')}`;actions=[text('Pause deployment or market placement','Pausar el despliegue o puesta en el mercado'),text('Obtain fact-specific legal review','Obtener revisión jurídica específica'),text('Document any claimed exception and safeguards','Documentar cualquier excepción y salvaguarda')];}
else if(product||(annex&&!exception)){level='high';title=text('Potential high-risk AI system','Posible sistema de IA de alto riesgo');basis=product?'Article 6(1) · Annex I product-safety route':`Article 6(2) · Annex III: ${annex}`;actions=[text('Confirm operator role and intended purpose','Confirmar rol del operador y finalidad prevista'),text('Perform formal Article 6 classification','Realizar clasificación formal del artículo 6'),text('Map provider/deployer obligations and evidence','Mapear obligaciones y evidencias del proveedor/responsable')];}
else if(annex&&exception){level='review';title=text('Annex III use with possible Article 6(3) exception','Uso del anexo III con posible excepción del artículo 6(3)');basis=`Article 6(3) · Annex III: ${annex}`;actions=[text('Document why the system does not pose significant risk','Documentar por qué el sistema no presenta riesgo significativo'),text('Confirm it does not perform profiling','Confirmar que no realiza perfiles'),text('Retain the assessment and monitor changes','Conservar la evaluación y vigilar cambios')];}
else if(transparency.length){level='transparency';title=text('Specific transparency obligations may apply','Pueden aplicarse obligaciones específicas de transparencia');basis=`Article 50 · ${transparency.join('; ')}`;actions=[text('Design appropriate notices or machine-readable marking','Diseñar avisos o marcado legible por máquina'),text('Check exceptions and the responsible operator','Comprobar excepciones y operador responsable'),text('Test that disclosures are clear and timely','Comprobar que la información sea clara y oportuna')];}
else{level='minimal';title=text('No elevated category identified by this screen','Este filtro no identifica una categoría elevada');basis=text('Minimal/other risk — voluntary codes and other law may still apply','Riesgo mínimo/otro: pueden aplicar códigos voluntarios y otras leyes');actions=[text('Maintain an AI inventory and proportionate risk assessment','Mantener inventario de IA y evaluación proporcionada'),text('Check GDPR, consumer, employment and sector law','Comprobar RGPD y normativa sectorial, laboral y de consumo'),text('Reassess after material changes','Reevaluar tras cambios materiales')];}
const uncertainty=[];if(role==='unknown')uncertainty.push(text('Organisation role is unresolved.','El rol de la organización está pendiente.'));if(!annex&&!product)uncertainty.push(text('Confirm that no Annex I or Annex III use applies.','Confirma que no aplica ningún uso de los anexos I o III.'));
result.className=`card result ${level}`;result.innerHTML=`<div class="sticky"><span class="eyebrow">${text('PRELIMINARY RESULT','RESULTADO PRELIMINAR')}</span><span class="pill">${level.toUpperCase()}</span><h2>${title}</h2><p><strong>${name}</strong></p><h3>${text('Decision basis','Base de decisión')}</h3><p>${basis}</p><h3>${text('Recommended next actions','Próximas acciones recomendadas')}</h3><ol>${actions.map(a=>`<li>${a}</li>`).join('')}</ol>${uncertainty.length?`<h3>${text('Uncertainties','Incertidumbres')}</h3><ul>${uncertainty.map(a=>`<li>${a}</li>`).join('')}</ul>`:''}<button class="ghost" onclick="window.print()">${text('Print / Save PDF','Imprimir / Guardar PDF')}</button><div class="result-cta"><strong>${text('Need a defensible assessment?','¿Necesitas una evaluación defendible?')}</strong><p>${text('SpectraSec can help validate the classification and define the next compliance actions.','SpectraSec puede ayudarte a validar la clasificación y definir las siguientes acciones de cumplimiento.')}</p><a href="https://www.spectrasec.eu/" target="_blank" rel="noreferrer">${text('Talk to SpectraSec','Hablar con SpectraSec')} →</a></div><p class="small">${text('Preliminary decision support only. Not legal advice.','Solo apoyo preliminar. No constituye asesoramiento jurídico.')}</p></div>`;result.scrollIntoView({behavior:'smooth',block:'start'});});
