export const VERSION='1.0.0';
const yes=(a,k)=>a[k]===true;
export function classify(a={}){const findings=[],triggers=[],uncertainties=[],obligations=[];let primary={code:'minimal',label:'No elevated category identified',article:'Voluntary codes / other law',severity:1};
if(a.euNexus===false)return{primary:{code:'out',label:'Potentially outside territorial scope',article:'Article 2',severity:0},findings:['No EU nexus was confirmed.'],triggers:['Territorial-scope answer'],uncertainties:['Extraterritorial effects and use of outputs in the EU require verification.'],obligations:['Document the territorial-scope analysis.'],confidence:'low'};if(a.euNexus!==true)uncertainties.push('Territorial scope remains unresolved.');
if(a.aiSystem==='no')return{primary:{code:'out',label:'Potentially not an AI system',article:'Article 3(1)',severity:0},findings:['The described system may fall outside the AI-system definition.'],triggers:['AI-system definition answer'],uncertainties:['Reassess against Commission guidance and actual technical design.'],obligations:['Document the definition analysis and monitor design changes.'],confidence:'medium'};
if(a.aiSystem!=='yes')uncertainties.push('AI-system definition remains unresolved.');if(a.excluded)findings.push('A potential Article 2 exclusion was selected; verify every condition.');
const prohibited=Object.entries(a.prohibited||{}).filter(([,v])=>v===true).map(([k])=>k);if(prohibited.length){primary={code:'prohibited',label:'Potential prohibited AI practice',article:'Article 5',severity:5};triggers.push(...prohibited);obligations.push('Pause deployment or market placement pending fact-specific review.','Document claimed exceptions and safeguards.');}
const highProduct=yes(a,'annexI')&&yes(a,'thirdPartyAssessment'),annex=Array.isArray(a.annexIII)?a.annexIII:[],exceptionClaim=yes(a,'article63')&&!yes(a,'profiling');if(primary.severity<4&&(highProduct||(annex.length&&!exceptionClaim))){primary={code:'high',label:'Potential high-risk AI system',article:highProduct?'Article 6(1) · Annex I':'Article 6(2) · Annex III',severity:4};triggers.push(...(highProduct?['Regulated product / safety component']:annex));obligations.push('Confirm provider and deployer roles.','Plan risk management, data governance, documentation, logging, transparency, human oversight, accuracy, robustness and cybersecurity.');}
if(primary.severity<3&&annex.length&&exceptionClaim){primary={code:'exception',label:'Annex III use with potential Article 6(3) exception',article:'Article 6(3)',severity:3};triggers.push(...annex,'Claimed narrow-task exception');obligations.push('Document why the system does not pose significant risk.','Retain and reassess after material changes.');}if(yes(a,'profiling')&&annex.length)uncertainties.push('Profiling prevents reliance on Article 6(3).');
const transparency=Object.entries(a.transparency||{}).filter(([,v])=>v===true).map(([k])=>k);if(transparency.length){findings.push('Specific transparency obligations may apply.');triggers.push(...transparency);obligations.push('Implement disclosure, labelling or machine-readable marking as applicable.');if(primary.severity<2)primary={code:'transparency',label:'Specific transparency obligations may apply',article:'Article 50',severity:2};}
if(a.gpai==='provider'){findings.push('The organisation may provide a general-purpose AI model.');obligations.push('Assess GPAI documentation, copyright and downstream-information duties.');}if(a.systemicRisk){findings.push('Potential GPAI systemic-risk indicators require specialist assessment.');obligations.push('Assess systemic-risk evaluation, incident reporting and cybersecurity duties.');}
if(!a.role||a.role==='unknown')uncertainties.push('Operator role is unresolved.');if(!a.purpose||a.purpose.trim().length<25)uncertainties.push('Intended purpose lacks sufficient detail.');if(!highProduct&&!annex.length)uncertainties.push('Confirm no Annex I or Annex III route applies.');if(!findings.length)findings.push('No prohibited, high-risk or specific transparency category was identified.');const confidence=uncertainties.length>=3?'low':uncertainties.length<=1?'high':'medium';return{primary,findings:[...new Set(findings)],triggers:[...new Set(triggers)],uncertainties:[...new Set(uncertainties)],obligations:[...new Set(obligations)],confidence};}
export function actionPlan(r){return{seven:r.primary.code==='prohibited'?['Pause the activity','Escalate to legal and executive owners','Preserve the decision record']:['Resolve missing facts','Confirm intended purpose and role','Assign an accountable owner'],thirty:r.primary.code==='high'?['Complete formal classification','Map applicable obligations','Create an evidence plan']:['Validate the classification','Implement applicable notices','Record proportionate controls'],ninety:['Approve the decision record','Test controls and human oversight','Schedule reassessment after changes']};}
