import{WORKBENCH_VERSION,TIMELINE,obligationsFor,exceptionStatus,buildRecord}from'./workbench-core.js';
const KEY='spectrasec-ai-workbench-v11',p=new URLSearchParams(location.search);let lang=p.get('lang')==='es'?'es':'en';
const t=(en,es)=>lang==='es'?es:en,esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let s={systemId:'',systemVersion:'',owner:'',reviewer:'',approver:'',reviewDate:'',affected:'',dataCategories:'',roles:[],annexIII:false,profiling:false,basis:'',evidence:'',article50:false,gpai:false,decision:'',uncertainties:'',history:[],...JSON.parse(localStorage.getItem(KEY)||'{}')};
const root=document.querySelector('#assurance-workbench'),roles=[['provider','Provider','Proveedor'],['deployer','Deployer','Responsable del despliegue'],['importer','Importer','Importador'],['distributor','Distributor','Distribuidor'],['representative','Authorised representative','Representante autorizado'],['manufacturer','Product manufacturer','Fabricante del producto']];
function field(k,en,es,type='text'){return`<label><span>${t(en,es)}</span><input id="w-${k}" type="${type}" value="${esc(s[k])}"></label>`}
function render(){const status=exceptionStatus(s),rows=obligationsFor(s.roles,{article50:s.article50,gpai:s.gpai});root.innerHTML=`<div class="wb-shell"><header class="wb-head"><div><p class="eyebrow">V1.1 · CLASSIFICATION & COMPLIANCE WORKBENCH</p><h2 id="workbench-title">${t('Build a defensible AI Act decision record','Crea un expediente defendible del Reglamento de IA')}</h2><p>${t('Separate classification from role-specific duties, evidence and approval. Data stays in this browser.','Separa la clasificación de obligaciones por rol, evidencias y aprobación. Los datos permanecen en este navegador.')}</p></div><b>${WORKBENCH_VERSION}</b></header>
<section class="wb-card timeline"><h3>${t('Regulatory application timeline','Calendario de aplicación')}</h3><div>${TIMELINE.map(([d,en,es])=>`<a href="https://digital-strategy.ec.europa.eu/en/faqs/navigating-ai-act" target="_blank" rel="noopener"><time>${d}</time><strong>${t(en,es)}</strong><small>${t('Official Commission source ↗','Fuente oficial de la Comisión ↗')}</small></a>`).join('')}</div><p>${t('Verify the current official timeline before relying on these dates.','Verifica el calendario oficial vigente antes de utilizar estas fechas.')}</p></section>
<div class="wb-grid"><section class="wb-card"><h3>01 · ${t('Decision record','Expediente de decisión')}</h3><div class="wb-fields">${field('systemId','System ID','ID del sistema')}${field('systemVersion','System version','Versión')}${field('owner','Accountable owner','Responsable')}${field('reviewer','Independent reviewer','Revisor independiente')}${field('approver','Approver','Aprobador')}${field('reviewDate','Next review','Próxima revisión','date')}</div><label><span>${t('Affected people','Personas afectadas')}</span><textarea id="w-affected">${esc(s.affected)}</textarea></label><label><span>${t('Data categories','Categorías de datos')}</span><textarea id="w-dataCategories">${esc(s.dataCategories)}</textarea></label></section>
<section class="wb-card"><h3>02 · ${t('Multi-role analysis','Análisis multirrol')}</h3><p>${t('Select every role actually performed.','Selecciona todos los roles realmente desempeñados.')}</p><div class="checks">${roles.map(([v,en,es])=>`<label><input data-role="${v}" type="checkbox" ${s.roles.includes(v)?'checked':''}><span>${t(en,es)}</span></label>`).join('')}</div><label class="inline"><input id="w-gpai" type="checkbox" ${s.gpai?'checked':''}> ${t('GPAI provider or downstream integrator review','Revisión de proveedor o integrador GPAI')}</label></section>
<section class="wb-card"><h3>03 · ${t('Article 6(3) exception workbench','Workbench de excepción del artículo 6(3)')}</h3><label class="inline"><input id="w-annexIII" type="checkbox" ${s.annexIII?'checked':''}> ${t('Annex III route identified','Ruta del anexo III identificada')}</label><label class="inline"><input id="w-profiling" type="checkbox" ${s.profiling?'checked':''}> ${t('Profiles natural persons — exception blocked','Perfila personas — excepción bloqueada')}</label><label><span>${t('Exception basis','Fundamento de la excepción')}</span><select id="w-basis"><option value="">${t('Select…','Seleccionar…')}</option>${[['narrow','Narrow procedural task','Tarea procedimental limitada'],['improve','Improves a completed activity','Mejora una actividad terminada'],['pattern','Pattern detection without replacing assessment','Detección de patrones sin sustituir evaluación'],['preparatory','Preparatory task','Tarea preparatoria']].map(([v,en,es])=>`<option value="${v}" ${s.basis===v?'selected':''}>${t(en,es)}</option>`).join('')}</select></label><label><span>${t('Evidence and significant-risk rationale','Evidencia y justificación de riesgo significativo')}</span><textarea id="w-evidence">${esc(s.evidence)}</textarea></label><strong class="status ${status}">${({na:t('Not assessed','No evaluada'),blocked:t('Blocked by profiling guard','Bloqueada por perfilado'),unsupported:t('Evidence incomplete','Evidencia incompleta'),documented:t('Documented; specialist validation required','Documentada; requiere validación especializada')})[status]}</strong></section>
<section class="wb-card"><h3>04 · ${t('Article 50 & GPAI','Artículo 50 y GPAI')}</h3><label class="inline"><input id="w-article50" type="checkbox" ${s.article50?'checked':''}> ${t('Human interaction, synthetic content or deepfake review','Revisión de interacción, contenido sintético o deepfake')}</label><p>${t('The evidence matrix adds disclosure and machine-readable marking controls. GPAI adds documentation, copyright and downstream information.','La matriz añade controles de aviso y marcado legible por máquina. GPAI añade documentación, derechos de autor e información aguas abajo.')}</p></section></div>
<section class="wb-card wide"><h3>05 · ${t('Role-specific obligations and evidence','Obligaciones y evidencias por rol')}</h3>${rows.length?`<div class="table"><table><thead><tr><th>${t('Role','Rol')}</th><th>${t('Obligation','Obligación')}</th><th>${t('Route','Ruta')}</th><th>${t('Evidence','Evidencia')}</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.role}</td><td>${t(r.en,r.es)}</td><td>${r.article}</td><td><select><option>${t('Pending','Pendiente')}</option><option>${t('Draft','Borrador')}</option><option>${t('Verified','Verificada')}</option><option>N/A</option></select></td></tr>`).join('')}</tbody></table></div>`:`<p>${t('Select roles to generate the matrix.','Selecciona roles para generar la matriz.')}</p>`}</section>
<section class="wb-card wide"><h3>06 · ${t('Decision, uncertainty and approval','Decisión, incertidumbre y aprobación')}</h3><div class="wb-fields"><label><span>${t('Decision and discarded routes','Decisión y rutas descartadas')}</span><textarea id="w-decision">${esc(s.decision)}</textarea></label><label><span>${t('Open uncertainties','Incertidumbres abiertas')}</span><textarea id="w-uncertainties">${esc(s.uncertainties)}</textarea></label></div><div class="actions"><button id="w-save" class="primary">${t('Save record','Guardar expediente')}</button><button id="w-json" class="secondary">JSON</button><button id="w-md" class="secondary">Markdown</button><button id="w-print" class="secondary">${t('Print / PDF','Imprimir / PDF')}</button></div></section>
<aside class="wb-cta"><div><strong>${t('Need independent validation?','¿Necesitas validación independiente?')}</strong><p>${t('SpectraSec can validate the classification and operationalise the controls.','SpectraSec puede validar la clasificación y operacionalizar los controles.')}</p></div><a href="https://www.spectrasec.eu/" target="_blank" rel="noopener">${t('Request an assessment','Solicitar evaluación')} →</a></aside></div>`;bind()}
function capture(){root.querySelectorAll('[id^="w-"]').forEach(e=>{const k=e.id.slice(2);if(['save','json','md','print'].includes(k))return;s[k]=e.type==='checkbox'?e.checked:e.value});s.roles=[...root.querySelectorAll('[data-role]:checked')].map(e=>e.dataset.role)}
function record(){capture();return buildRecord({...s,obligations:obligationsFor(s.roles,{article50:s.article50,gpai:s.gpai}),officialSources:['https://digital-strategy.ec.europa.eu/en/faqs/navigating-ai-act','https://digital-strategy.ec.europa.eu/en/faqs/transparency-obligations-under-article-50-ai-act','https://digital-strategy.ec.europa.eu/en/faqs/guidelines-obligations-general-purpose-ai-providers']})}
function bind(){root.querySelectorAll('input,select,textarea').forEach(e=>e.onchange=()=>{capture();localStorage.setItem(KEY,JSON.stringify(s));render()});root.querySelector('#w-save').onclick=e=>{e.preventDefault();capture();s.history.push({at:new Date().toISOString(),event:'saved',owner:s.owner});localStorage.setItem(KEY,JSON.stringify(s));e.target.textContent=t('Saved ✓','Guardado ✓')};root.querySelector('#w-json').onclick=e=>{e.preventDefault();download('eu-ai-act-decision-record.json',JSON.stringify(record(),null,2),'application/json')};root.querySelector('#w-md').onclick=e=>{e.preventDefault();const r=record(),md=`# EU AI Act Decision Record\n\n- Version: ${r.version}\n- System: ${r.systemId}\n- Roles: ${r.roles.join(', ')}\n- Owner: ${r.owner}\n- Reviewer: ${r.reviewer}\n- Approver: ${r.approver}\n\n## Decision\n${r.decision}\n\n## Uncertainties\n${r.uncertainties}\n\n## Obligations\n${r.obligations.map(x=>`- [ ] ${x.role}: ${lang==='es'?x.es:x.en} (${x.article})`).join('\n')}\n\n_Preliminary support; not legal advice._`;download('eu-ai-act-decision-record.md',md,'text/markdown')};root.querySelector('#w-print').onclick=e=>{e.preventDefault();print()}}
function download(n,c,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
const language=document.querySelector('#language');language.onclick=()=>{capture();lang=lang==='en'?'es':'en';p.set('lang',lang);history.replaceState(null,'',`${location.pathname}?${p}`);language.textContent=lang==='en'?'ES':'EN';render();document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[lang]);document.documentElement.lang=lang};language.textContent=lang==='en'?'ES':'EN';render();document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[lang]);document.documentElement.lang=lang;
