import{mkdir,writeFile}from'node:fs/promises';
const base='https://cyber-g3.github.io/eu-ai-act-risk-classifier';
const pages=[
['eu-ai-act-high-risk-classifier','EU AI Act high-risk classifier','Determine whether Article 6 and Annex I or Annex III may place an AI system in the high-risk category.','High-risk classification depends on the intended purpose, product-safety role, Annex III use case and the Article 6(3) exception analysis. Document assumptions and unresolved facts.'],
['article-6-3-exception','EU AI Act Article 6(3) exception','Understand the limited Article 6(3) route and why profiling excludes reliance on the exception.','Article 6(3) requires a fact-specific analysis of whether an Annex III system poses a significant risk of harm. It is not a general exemption and the assessment should be documented.'],
['article-50-transparency','EU AI Act Article 50 transparency obligations','Screen AI systems for interaction, synthetic content, emotion recognition and deepfake transparency duties.','Article 50 contains transparency duties for specific systems and outputs. The applicable duty depends on role, functionality, content and context.'],
['ai-provider-vs-deployer','AI provider vs deployer under the EU AI Act','Compare provider, deployer, importer, distributor and product-manufacturer roles.','Role is determined by facts such as development, branding, placing on the market, putting into service and operational use. One organisation can hold more than one role.'],
['gpai-obligations','General-purpose AI obligations','Screen GPAI provider status, documentation, copyright and systemic-risk obligations.','General-purpose AI models have a distinct regulatory route. Providers should assess model capability, systemic-risk thresholds, documentation and downstream information duties.']];
const render=(title,description,body,path,lang='en')=>`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | SpectraSec</title><meta name="description" content="${description}"><link rel="canonical" href="${base}/${path}/"><meta property="og:image" content="${base}/assets/social-preview.jpg"><meta name="robots" content="index,follow"><style>body{font:18px/1.65 system-ui;max-width:900px;margin:60px auto;padding:24px;color:#142536}a{color:#0b6657}.cta{display:inline-block;background:#0b6657;color:white;padding:12px 18px;border-radius:8px;text-decoration:none}nav{display:flex;gap:18px;flex-wrap:wrap}.note{background:#edf5f3;padding:18px;border-radius:10px}</style></head><body><nav><a href="${base}/">EU AI Act Tool</a><a href="https://cyber-g3.github.io/nis2-applicability-triage-by-country/">NIS2 Scope</a><a href="https://cyber-g3.github.io/audit-evidence-readiness-checker/">Audit Evidence</a></nav><h1>${title}</h1><p>${body}</p><h2>What the decision record should contain</h2><ul><li>Intended purpose and system boundaries.</li><li>Operator role and territorial scope.</li><li>Triggered articles and supporting facts.</li><li>Uncertainty, owner and next review.</li></ul><h2>Frequently asked question</h2><h3>Is the tool a legal classification?</h3><p>No. It is preliminary decision support and requires validation against the regulation, guidance and the system facts.</p><p><a class="cta" href="${base}/">Open the free classifier →</a></p></body></html>`;
const urls=[`${base}/`,`${base}/en/`,`${base}/es/`];for(const[p,t,d,b]of pages){await mkdir(p,{recursive:true});await writeFile(`${p}/index.html`,render(t,d,b,p));urls.push(`${base}/${p}/`)}
for(const[lang,title,desc]of[['en','EU AI Act risk assessment','Classify risk, operator role and initial obligations.'],['es','Evaluación de riesgo del Reglamento de IA','Clasifica riesgo, rol del operador y obligaciones iniciales.']]){await mkdir(lang,{recursive:true});await writeFile(`${lang}/index.html`,render(title,desc,desc,lang,lang))}
await writeFile('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${base}/sitemap.xml\n`);await writeFile('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(x=>`<url><loc>${x}</loc></url>`).join('')}</urlset>`);
